global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mongodb-query-exporter'
    static_configs:
      - targets: ['mongodb-query-exporter:9412']
  - job_name: 'jenkins_job'
    metrics_path: /prometheus/
    static_configs:
    - targets: ['host.docker.internal:8080']
